config/routes.rb
Rails.application.routes.draw do

  root "pages#index"

  get '/search' => 'offers#search'

  get 'review/show'

  get 'review/new'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :bookings

  resources :offers do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings do
    resources :reviews, only: [:index, :show, :new, :create]
  end

  get "/cities" => "cities#cities", as: :cities

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  has_one :review, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :full_price, presence: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :location, presence: true
  validates :price_per_day, presence: true

  geocoded_by :location

  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      obj.country = geo.country
    end
  end

  after_validation :geocode, if: :location_changed?
  after_validation :reverse_geocode, if: :location_changed?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one :offer, dependent: :destroy

  mount_uploader :image, PhotoUploader

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def create_offer(args)
    super(args) unless self.offer
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nanny, :image, :image_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nanny, :image, :image_cache])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking

  def index
    @bookings = current_user.bookings
  end

  def show

  end

  def new
    @booking = current_user.bookings.new()
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @booking = @offer.bookings.build(booking_params)
    @booking.user = current_user
    # calculate full
    elapsed_time = (@booking.end_date - @booking.start_date)
    @booking.full_price = @offer.price_per_day * elapsed_time + 50
    @booking.save
    redirect_to booking_path(@booking)
    # redirect_to
  end

  def edit
  end

  def update
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  def total_price

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      if current_user
        @booking = current_user.bookings.find_by(id: params[:id])
      else
        redirect_to new_user_session_path
      end
    end

    # Only allow a trusted parameter "white list" through.
    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :full_price)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def cities
    @countries = Offer.where.not(country: nil).map{ |offer| offer.country }.uniq.sort
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    #@offer = current_user.offer
    if params[:search]
      @offers = Offer.where('location ILIKE ?', params[:search])
      flash.now[:notice] = "There are #{@offers.size} in this category".html_safe
    elsif params[:location]
      @offers = Offer.where(:location => params[:location])
      flash.now[:notice] = "There are #{@offers.size} in this category".html_safe
    elsif params[:country]
      @offers = Offer.where(:country => params[:country])
      flash.now[:notice] = "There are #{@offers.size} in this category".html_safe
    else
      @offers = Offer.where.not(latitude: nil, longitude: nil)
    end
    @hash = Gmaps4rails.build_markers(@offers) do |offer, marker|
      marker.lat offer.latitude
      marker.lng offer.longitude
        # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def new
    @offer = Offer.new
  end

  def show
    @booking = Booking.new
    @offer = Offer.find(params[:id])
    @offer_coordinates = { lat: @offer.latitude, lng: @offer.longitude }
  end

  def create
    if user_signed_in? && current_user.nanny?
      @offer = current_user.create_offer(offer_params)
      redirect_to offers_path
    else
      redirect_to user_session_path
    end
  end

  def edit
    @offer = current_user.offer
  end

  def update
    @offer = current_user.offer.update(offer_params)
    redirect_to offers_path
  end

  def destroy
    @offer = current_user.offer.destroy
    redirect_to new_offer_path
  end

private

  def offer_params
    params.require(:offer).permit(:location, :price_per_day, :superpower, :video, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_booking, only: [ :new, :create, :show]

  def index
    @booking = Booking.all
  end


  def show
    @review = Review.find[params:id]
  end

  def new
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render 'bookings/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_booking
    @booking = Booking.find(params[:booking_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for @booking do |f| %>
  <div class="form-inputs">
    <%= f.input :start_date, required: true, autofocus: true %>
    <%= f.input :end_date, required: true %>
    <%= f.input :full_price %>
    <%= f.input :offer_id, as: :hidden, input_html: {value: params[:offer_id]} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit booking" %>
  </div>
<% end %>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container">

  <h1>These are your bookings</h1>
  <p>Manage your bookings here</p>

  <table class= "table table-hover">
    <thead>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Nanny</th>
        <th>Location</th>
        <th>Full Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.start_date %></td>
          <td><%= booking.end_date %></td>
          <td><%= booking.offer.user.first_name %></td>
          <td><%= booking.offer.location %></td>
          <td><%= booking.full_price %> USD</td>
          <td><%= link_to 'Show', booking_path(booking) %> </td>
        <% unless current_user.nanny? %>
          <td><%= link_to 'Cancel', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
          <td><%= link_to 'Add review', new_booking_review_path(booking) %> </td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/bookings/new.html.erb
<div class="container">


  <p>New booking for Offer from <%= Offer.find_by(id:params["offer_id"]).user.first_name %></p>

  <%= render "form" %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Booking Summary</h1>
  <p>Find the Booking Details here:</p>

  <p><b>Your Nanny is: <%= @booking.offer.user.first_name %></b></p>
  <%= cl_image_tag @booking.offer.user.image, class:"avatar avatar-large" %>
  <p><b>Total Price: </b><%= @booking.full_price %> USD</p>
  <p><b>Location: </b><%= @booking.offer.location %></p>
  <p><b>From </b><%= @booking.start_date %> <b> to </b> <%= @booking.end_date %></p>


  <div id="reviews">
  <% if @booking.review.blank? %>
    Be the first to leave a review for <%= @booking.offer.user.first_name %>
  <% else %>
      <%= render 'reviews/show', review: @booking.review %>
  <% end %>
</div>

  <p><%= link_to 'Back to all Bookings', bookings_path %> </p>
  <% unless current_user.nanny? %>
     <p><td><%= link_to 'Cancel Booking', booking_path(@booking), method: :delete, data: { confirm: 'Are you sure?' } %> </td></p>
     <p><td><%= link_to 'Add review', new_booking_review_path(@booking) %> </td></p>
  <% end %>
</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/cities/cities.html.erb
<h1 class="text-center"><strong>Where is your next destination?</strong></h1>

<div class="container text">

  <table>
    <thead>
      <tr>
        <th><h3>Countries(A-Z)</h3></th>
        <th colspan="3"></th>
      </tr>
    </thead>



  <!-- put each city in the right category -->

    <tbody>
      <div class="container">
        <% @countries.each do |c| %>
          <tr>
            <td class="lobster"><%= link_to c, offers_path(:country=> c ) %></td>
          </tr>
        <% end %>

    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelNanny</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href='https://fonts.googleapis.com/css?family=Raleway|Lobster' rel='stylesheet' type='text/css'>

  </head>

  <body class="<%=controller_name%>">
    <%= render 'shared/flashes' %>
    <%= render "shared/navbar" %>
      <%= yield %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>

  <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for @offer do |f| %>
<div class="form-group col-lg-6">
  <div class="form-inputs">
    <%= f.input :location, required: true, autofocus: true %>
    <%= f.input :price_per_day, required: true %>
    <%= f.input :superpower %>
    <%= f.input :description, as: :text %>
    Enter your YouTube URL <%= f.input :video %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Create offer" %>
  </div>
<% end %>
</div>

app/views/offers/create.html.erb
<h1>Offers#create</h1>
<p>Find me in app/views/offers/create.html.erb</p>

app/views/offers/destroy.html.erb
<h1>Offers#destroy</h1>
<p>Find me in app/views/offers/destroy.html.erb</p>

app/views/offers/edit.html.erb
<div class="container">

  <h1>You're a nanny?</h1>
  <p>Please enter your information below. As a video you can enter a YouTube link.</p>

  <%= render "form" %>
</div>

app/views/offers/index.html.erb
<!-- List of all Offers/Nannys -->

<div class="container">
  <h1>List of all Nannys</h1>
  <div class="row">
  <% @offers.each do |offer| %>
  <div class="col-md-2 col-xs-4">
    <div class="text-box">
    <%= link_to offer do %>
    <%= cl_image_tag offer.user.image, class:"avatar avatar-large" %>
      <div class="avatar-name">
        <p><%= offer.user.first_name %></p>
      </div>
      <div class="avatar-description">
      <p><%= offer.location %></p>
      <p><b><%= offer.price_per_day %> USD</b></p>
      </div>
    <% end %>
    </div>
  </div>
  <% end %>
</div>
</div>

<!-- Map -->
<div id="map" style="width: 100%; height: 600px;"></div>
<% content_for(:after_js) do %>
  <%= javascript_tag do %>

    $(document).ready(function() {
      console.log("document ready");
      var handler = Gmaps.build('Google');
      handler.buildMap({
        internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/offers/new.html.erb
<div class="container">
<h1>Create a new offer</h1>
<p>Please enter the required information for parents to book you!</p>

<%= render "form" %>
</div>

app/views/offers/show.html.erb
<div class="container">
    <%= link_to 'Back', offers_path %></td>
    <h1>Nanny in <%= @offer.location %></h1>
</div>

<!-- User Picture and User Name -->
<div class="container">
  <div class="col-md-6">
    <div class="offer-profile">
      <% if @offer.user.facebook_picture_url %>
        <%= cl_image_tag @offer.user.facebook_picture_url, class:"avatar avatar-large" %>
      <% end%>
      <% if @offer.user.image %>
        <%= cl_image_tag @offer.user.image, class:"avatar avatar-large" %>
      <% end%>
        <br>
      <p><b><%= @offer.user.first_name %> <%= @offer.user.last_name %></b></p>
    </div>
  </div>
    <div class="col-md-6">
    <%if @offer.superpower %>
      <h4>My Superpowers</h4>
       <%= @offer.superpower %>
      <!-- Offer Superpower -->
    <% end %>
    </div>
  </div>
</div>

 <!-- Offer Video and Offer price per Day -->
<div class="container">
  <div class="col-md-6">
    <div class="embed-container">
      <% if @offer.video %>
        <%= embed(@offer.video) %>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
  <div class="booking-form">
  <p><b>Book <%= @offer.user.first_name %> as a Nanny</b></p>
  <table>
    <thead>
      <th colspan="2"></th>
    </thead>
    <tbody>
    <tr>
      <td><p>Select Date </p></td>
    <td>
    <%= simple_form_for [@offer, @booking] do |f| %>
      <div class="form-inputs">
        <div class="input-daterange input-group" id="datepicker">
          <%= f.input :start_date, as: :string, required: true, label: false, input_html: { class: 'input-sm form-control start-date' } %>
          <span class="input-group-addon">to</span>
          <%= f.input :end_date, as: :string, required: true, label: false, input_html: { class: 'input-sm form-control end-date'} %>
        </div>
      </div>
    </td>
    </tr>
    <tr>
      <td><p>Price per day:</p></td>
      <td class="text-right"><p><span class="price_per_day"><%= @offer.price_per_day %></span> USD</p></td>
    </tr>
    <tr>
      <td><p>Fees:</p></td>
      <td class="text-right"><p> 50 USD</p></td>
    </tr>
    <tr>
      <td><p><b>Total Price:</p></td>
      <td class="text-right"><p><span class="full-price"><%= @offer.price_per_day + 50 %></span> USD</b></p></td>
    </tr>
    <tr>
      <td><%= f.submit "Create booking", :class => 'btn create_booking' %></td>
    </tr>
    <% end %>
    </tr>
    </tbody>
  </table>
  </div>
  </div>
</div>

<!-- Offer Description-->
<div class="container">
  <p><b>About me</b></p>
  <p><%= @offer.description %></p>
</div>


<!-- Add Offer Review-->
<div class="container">
  <h4>Reviews</h4>
  <ul class="dashed">
  <p><% @offer.reviews.each do |review|%></p>
   <li> <%= review.content %></li>
  <%end %>
  </ul>
</div>

<!-- Javascript-->
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $('.input-daterange').datepicker({
        todayHighlight: true,
        format: "yyyy-mm-dd"
    });
    $(document).ready(function(){
      $("#booking_end_date").on("change", function(event){
      var end_date = $("#booking_end_date").datepicker("getDate");
      var start_date = $("#booking_start_date").datepicker("getDate");
      var num_days = (end_date - start_date)/86400000;
        if (num_days == 0) {
          num_days = 1;
          end_date.setTime(end_date.getTime() + (1000*60*60*24))
         $('#booking_end_date').datepicker("setDate", end_date);
        }
      var price_per_day = parseInt($(".price_per_day").text());
      var fee = 50;
      var full_price = (end_date - start_date)/86400000 * price_per_day + fee;
      $(".full-price").text(full_price);
      });
    });
  <% end %>
<% end %>

</div>

app/views/offers/update.html.erb
<h1>Offers#update</h1>
<p>Find me in app/views/offers/update.html.erb</p>

app/views/pages/cities.html.erb
<h1><strong>Where is your next destination?</strong></h1>

<table>
  <thead>
    <tr>
      <th>Countries</th>
      <th colspan="3"></th>
    </tr>
  </thead>



<!-- put each city in the right category -->

 <tbody>
    <% @countries.each do |c| %>
      <tr>
        <td><%= c %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/index.html.erb
<!-- Homepage Banenr -->

<div class="banner">
  <div class="banner-content">
    <h1>Welcome to TravelNanny</h1>
    <p>Book a nanny now because you deserve to be on vacation while on vacation!</p>
      <div class="search" >
        <div class="form-inline">
          <form action='/offers'>
          <input type="text" class="form-control" name="search" placeholder="Location">
          <input type="submit" class="btn" value="Search">
        </form>
      </div>

    </div>
  </div>
</div>

<!-- Travel Nanny Description -->

<div class="container">
  <div class="col-md-6">
    <div class="text-box">
      <h3 class="text-center">Why become a TravelNanny?</h3>
      <p class="text-justify">Not only will you be travelling the world but you will earn great money while doing it. If you are good with kids then do sign up and help make a family travel stress free!</p>
      <div class="text-center">
        <%= link_to 'Become a nanny!', edit_user_registration_path, {class: "btn btn-warning btn-lg"} %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="text-box">
      <h3 class="text-center">Why hire a TravelNanny?</h3>
      <p class="text-justify">Because finding good help while on vacation is always hard to find! Forget about carrying the diaper bag ! Travel stress free and pamper yourself by hiring a TravelNanny! Because you deserve it!</p>
      <div class="text-center">
        <%= link_to 'View all', offers_path, {class: "btn btn-warning btn-lg"} %>
      </div>
    </div>
  </div>
</div>

<!-- The Top 3 Cities -->

<div class="wrapper-grey padded">
  <div class="container">
  <h3 class="text-center">Where is your next destination?</h3>
    <div class="row">

      <div class="col-xs-12 col-sm-4">
        <%= link_to offers_path(:location=>"Paris") do %>
          <div class="card" id="paris-card" style="/*background-image: linear-gradient(-225deg, rgba(50,0,200,0.5) 0%, rgba(36,0,30,0.5) 50%), url('assets/card-paris.jpg');*/">
            <div class="card-description">
              <h3>Paris</h3>
              <p>Find a Nanny in Paris</p>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4">
        <%= link_to offers_path(:location=>"Brussel") do %>
          <div class="card" id="brussels-card" style="/*background-image: linear-gradient(-225deg, rgba(50,0,200,0.5) 0%, rgba(36,0,30,0.5) 50%), url('assets/card-brussels.jpeg');*/">
            <div class="card-description">
              <h3>Brussel</h3>
              <p>Find a Nanny in Brussels</p>
            </div>
        </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4">
        <%= link_to offers_path(:location=>"London") do %>
          <div class="card" id="london-card">
            <div class="card-description">
              <h3>London</h3>
              <p>Find a Nanny in London</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="text-center">
        <%= link_to 'View all', cities_path, {class: "btn btn-warning btn-lg"} %>
      </div>
  </div>
</div>

app/views/review/show.html.erb
<h1><strong> Reviews </strong></h1>

  <% @restaurant.reviews.each do |review| %>
    <p><strong>Content:</strong> <%= review.content %>,
    <br><strong>Rating:</strong> <%= review.rating %></p>

  <% end %>

app/views/reviews/_show.html.erb
<h1>Review</h1>
  <p><strong>Content:</strong> <%= review.content %>,
  <br><strong>Rating:</strong> <%= review.rating %></p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="inline">
        <%= image_tag "logo", width: '60px' %>
      </div>
      <div class="inline"><%= link_to "TravelNanny", root_path, class: "navbar-brand lobster" %></div>
    </div>



    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? == false %>
          <li class="links"><%= link_to "Sign up", new_user_registration_path %></li>
          <li class="links"><%= link_to "Log in", new_user_session_path %></li>
        <% end %>

        <% if user_signed_in? && current_user.facebook_picture_url %>
          <%= image_tag current_user.facebook_picture_url, height: 54, width: 55 %>
        <% elsif user_signed_in? && current_user.image_url %>
          <%= image_tag current_user.image, height: 54, width: 55 %>
        <% end %>

        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Profile", edit_user_registration_path %></li>
              <li> <% if current_user.offer %> </li>
                <li> <%= link_to "Edit Offer", edit_offer_path(current_user.offer.id) %> </li>
              <li> <% end %> </li>
              <li> <%= link_to "My Bookings", bookings_path %> </li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>